var nome = prompt('Digite seu nome.')
var idade = prompt('Digite sua idade ( apenas números ).')
var cidade = prompt('Digite a cidade em que você nasceu.')
var comida = window.prompt('Digite sua comida favorita.')
window.alert(`${nome} tem ${idade} anos, nasceu em ${cidade} e gosta de comer ${comida}. `)