let nome = prompt('Digite seu nome completo:')
let nomeC = document.getElementsByClassName('nome')[0]
nomeC.innerText = ' ' + nome
let end = prompt('Digite seu endereço:')
let endereco = document.getElementsByClassName('endereco')[0]
endereco.innerText = ' ' + end
let tel = prompt('Digite seu telefone:')
let telefone = document.getElementsByClassName('telefone')[0]
telefone.innerText = ' ' + tel
let email = prompt('Digite seu email:')
let email2 = document.getElementsByClassName('email')[0]
email2.innerText = ' ' + email
let cpf = prompt('Digite seu CPF:')
let cpf2 = document.getElementsByClassName('cpf')[0]
cpf2.innerText = ' ' + cpf
let cep = prompt('Digite seu cep')
let cep2 = document.getElementsByClassName('cep')[0]
cep2.innerText = ' ' + cep